const generalizations = 
[ 
    'patterns have segments that repeat', 
    'patterns are enablers', 
    'patterns allow for predictions', 
    'patterns have an internal order',
    'relationships are purposeful', 
    'relationships are powerful', 
    'relationships change over time', 
    'relationships follow rules', 
    'relationships are in everything',
    'order is a form of communication', 
    'order may be natural or constructed', 
    'order may have repeated patterns', 
    'order and chaos are reciprocals',
    'systems have parts that work together', 
    'systems follow rules', 
    'systems may be influenced by other systems', 
    'systems interact', 
    'systems are made up of other systems',
    'change can be positive or negative', 
    'change is inevitable', 
    'change can be natural or manmade', 
    'change is necessary for growth', 
    'change can be revolutionary or evolutionary',
    'power is the ability to influence', 
    'power may be used or abused', 
    'power may take many forms', 
    'power is always present in some form', 
    'power may be overt or covert',
    'structure has parts that are interrelate', 
    'structure may be combined to form larger structures', 
    'structure is no stronger than its weakest component', 
    'structure has parts that support and are supported',
    'force influences or changes', 
    'force attracts, holds, or repels', 
    'force may be countered with equal or greater force', 
    'force and inertia are codependent',
    'conflict may be natural or manmade', 
    'conflict may be intentional or unintentional', 
    'conflict is composed of opposing forces', 
    'conflict is progressive', 
    'conflict may allow for change and synthesis',
    'order and chaos are constantly moving toward and away from each other', 
    'order and chaos can be natural or human made', 
    'order vs chaos represents duality, transformation, symmetry, and asymmetry',
    'continuity is found in connectedness over time', 
    'continuity and discontinuity may be finite or infinite', 
    'continuity is related to strong relationships between past, present and anticipated patterns of thought, behavior, events, functions',
    'living things adapt over time', 
    'sometimes adaptation leads to survival, sometimes not', 
    'adaptation is related to time, change, and structure',
    'Add your own'
];

export {generalizations};